'use strict'
const PromoBanner = use('App/Models/PromoBanner')
const ThisLib = use('App/Lib/LoyaltyLib')
const validTarget = (req) => {
  const type = req.target_type || 'none'; if (!['none','product','internal_url','external_url'].includes(type)) return 'target_type tidak valid'
  if (type === 'product' && !req.target_item_id) return 'target_item_id wajib diisi'
  if (type === 'internal_url' && (!req.target_url || !`${req.target_url}`.startsWith('/'))) return 'URL internal harus diawali /'
  if (type === 'external_url' && !/^https:\/\//i.test(req.target_url || '')) return 'URL eksternal harus menggunakan https'
  return null
}
class PromoBannerController {
  async public_get ({ request, response }) { const now = new Date(); const partnerId = request.input('partner_id'); const query = PromoBanner.query().where('status','active').where('start_at','<=',now).where('end_at','>',now).orderBy('display_order','asc').orderBy('promo_banner_id','asc'); if (partnerId) query.where((b) => b.where('scope_type','all').orWhere('partner_id',partnerId)); else query.where('scope_type','all'); const data = await query.fetch(); return response.json({ status:true, data:data.toJSON() }) }
  async gets ({ request, response, auth }) { const q=PromoBanner.query().with('partner').orderBy('display_order','asc'); if(auth.user.type==='partner'){ const pid=await ThisLib.getPartnerIDFromUser(auth.user.user_id); q.where('partner_id',pid) } const data=await q.paginate(request.input('page',1),request.input('rows',10)); return response.json({status:true,data}) }
  async get ({request,response,auth}) { const row=await PromoBanner.query().where('promo_banner_id',request.input('promo_banner_id')).first(); if(!row) return response.status(404).json({status:false,message:'Promo tidak ditemukan'}); if(auth.user.type==='partner' && row.partner_id!==await ThisLib.getPartnerIDFromUser(auth.user.user_id)) return response.status(403).json({status:false,message:'Tidak diizinkan'}); return response.json({status:true,data:row}) }
  async save ({request,response,auth}) { const req=request.all(); const error=validTarget(req); if(error || !req.title || !req.image_url || !req.start_at || !req.end_at || new Date(req.end_at)<=new Date(req.start_at)) return response.badRequest({status:false,message:error || 'Judul, gambar, dan periode tayang wajib valid'}); let row=req.promo_banner_id ? await PromoBanner.find(req.promo_banner_id) : new PromoBanner(); if(!row) return response.status(404).json({status:false,message:'Promo tidak ditemukan'}); const pid=auth.user.type==='partner' ? await ThisLib.getPartnerIDFromUser(auth.user.user_id) : req.partner_id || null; if(auth.user.type==='partner' && row.promo_banner_id && row.partner_id!==pid) return response.status(403).json({status:false,message:'Tidak diizinkan'}); Object.assign(row,{title:req.title,image_url:req.image_url,status:req.status||'inactive',start_at:req.start_at,end_at:req.end_at,display_order:Number(req.display_order)||0,scope_type:pid?'partner':'all',partner_id:pid,target_type:req.target_type||'none',target_item_id:req.target_type==='product'?req.target_item_id:null,target_item_slug:req.target_type==='product'?(req.target_item_slug||null):null,target_url:['internal_url','external_url'].includes(req.target_type)?req.target_url:null,updated_by:auth.user.user_id}); if(!row.created_by) row.created_by=auth.user.user_id; await row.save(); return response.json({status:true,data:row,message:'Promo tersimpan'}) }
}
module.exports = PromoBannerController
